import Head from 'next/head';
import FormNovoClient from '../components/FormNovoClient';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className='bg-[#d6eaff] h-screen'>
      <Head>
        <title>NEXT | CRUD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      
      
      <Header />
      <main className='mt-16'>
        <FormNovoClient />
      </main>

    </div>
  )
}
